version: '3.3'
services:
  app:
    container_name: app
    image: ${APP_DOCKER_REPOSITORY}
    restart: always
    networks:
      - app-network

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - app
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
